server:
  port: 8080


spring:
  http:
    encoding:
      charset: UTF-8

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bluecat?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
#    password: linyous

# 管路员账号，以逗号分开
#manager.accounts: "123123,123123123"

  # 邮箱基本配置
  mail:
    # 配置 smtp 服务主机地址
    # qq 邮箱     smtp.qq.com    端口号 465 或 587
    # sina       smtp.sina.com
    # aliyun     smtp.aliyun.com
    # 163        smtp.163.com   端口号 465 或 994
    host: smtp.qq.com
    # 发送者邮箱
    username: xxxxxxxx@qq.com
    # 在邮箱内申请的授权码
    password:
    # 端口号
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 其他参数
    properties:
      mail:
        # 配置SSL 加密工厂
        smtp:
          ssl:
            # 本地测试， 先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    global-config:
      db-config:
        column-underline: true

file-save-path: "D:/IDEAWorkSpace/1/file/"

file-token-path: "sk-onZOIeQmV6syyOP7Ac71D9EfF45943Ed83CeC5348c45B2Aa"
